version: "3"
services:
  app:
    container_name: app
    restart: always
    build: ./app
    ports:
      - "80:4000"
    links:
      - mongo

  mongo:
    container_name: db
    image: mongo
    ports:
      - "27017:27017"

  client:
    container_name: web
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    links:
      - app
